# Generated by Django 5.0.4 on 2024-04-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instav2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
